#pragma once

namespace Pixel {
	enum MouseButton {
		PX_MOUSE_BUTTON_1 = 0,
		PX_MOUSE_BUTTON_2 = 1,
		PX_MOUSE_BUTTON_3 = 2,
		PX_MOUSE_BUTTON_4 = 3,
		PX_MOUSE_BUTTON_5 = 4,
		PX_MOUSE_BUTTON_6 = 5,
		PX_MOUSE_BUTTON_7 = 6,
		PX_MOUSE_BUTTON_8 = 7,
		PX_MOUSE_BUTTON_LAST = PX_MOUSE_BUTTON_8,
		PX_MOUSE_BUTTON_LEFT = PX_MOUSE_BUTTON_1,
		PX_MOUSE_BUTTON_RIGHT = PX_MOUSE_BUTTON_2,
		PX_MOUSE_BUTTON_MIDDLE = PX_MOUSE_BUTTON_3
	};
}